#!/usr/bin/env bash
#
# Generated by make build. Do not edit directly.
# Project: routeros_ssl
# Version: 0.0.0-dev
# Build date: unknown
# Build commit: unknown
# Maintained source: src/letsencrypt-routeros.bash
# Embedded dependency: bashlog.bash v0.0.18

ROUTEROS_SSL_PROJECT_NAME=routeros_ssl
ROUTEROS_SSL_VERSION=0.0.0-dev
ROUTEROS_SSL_BUILD_DATE=unknown
ROUTEROS_SSL_BUILD_COMMIT=unknown

BASHLOG_PROJECT_NAME=bashlog
BASHLOG_VERSION=0.0.18
BASHLOG_BUILD_DATE=2026-09-16T11:05:39-04:00
BASHLOG_BUILD_COMMIT=49351d22be4b


declare -g __bashlog_active_level=6

declare -g __bashlog_level_number=

declare -g __bashlog_level_name=

__bashlog_level_to_number() {
  if (( $# != 1 )); then
    return 64
  fi

  case $1 in
    emergency | 0) __bashlog_level_number=0 ;;
    alert | 1) __bashlog_level_number=1 ;;
    critical | 2) __bashlog_level_number=2 ;;
    error | 3) __bashlog_level_number=3 ;;
    warning | 4) __bashlog_level_number=4 ;;
    notice | 5) __bashlog_level_number=5 ;;
    info | 6) __bashlog_level_number=6 ;;
    debug | 7) __bashlog_level_number=7 ;;
    *) return 64 ;;
  esac

  return 0
}

__bashlog_level_to_name() {
  if (( $# != 1 )); then
    return 64
  fi

  case $1 in
    0) __bashlog_level_name=emergency ;;
    1) __bashlog_level_name=alert ;;
    2) __bashlog_level_name=critical ;;
    3) __bashlog_level_name=error ;;
    4) __bashlog_level_name=warning ;;
    5) __bashlog_level_name=notice ;;
    6) __bashlog_level_name=info ;;
    7) __bashlog_level_name=debug ;;
    *) return 64 ;;
  esac

  return 0
}

bashlog_level_get() {
  if (( $# != 0 )); then
    return 64
  fi

  __bashlog_level_to_name "${__bashlog_active_level}" || return 64
  printf '%s\n' "${__bashlog_level_name}"
}

bashlog_level_set() {
  local candidate

  if (( $# != 1 )); then
    return 64
  fi

  __bashlog_level_to_number "$1" || return 64
  candidate=${__bashlog_level_number}
  __bashlog_active_level=${candidate}
  return 0
}

declare -ga __bashlog_context_names=()

declare -ga __bashlog_context_states=()

declare -g __bashlog_context_count=0

declare -g __bashlog_context_index=-1

declare -ga __bashlog_rule_contexts=()

declare -ga __bashlog_rule_matchers=()

declare -ga __bashlog_rule_patterns=()

declare -ga __bashlog_rule_replacements=()

declare -g __bashlog_rule_count=0

declare -g __bashlog_match_start=-1

declare -g __bashlog_match_length=0

declare -g __bashlog_transform_result=

declare -g __bashlog_redacted_result=

__bashlog_context_name_valid() {
  local LC_ALL=C

  if (( $# != 1 )); then
    return 1
  fi

  [[ $1 =~ ^[A-Za-z_][A-Za-z0-9_.:-]*$ ]]
}

__bashlog_context_find() {
  local context=${1-}
  local index

  __bashlog_context_index=-1
  for ((index = 0; index < __bashlog_context_count; index++)); do
    if [ "${__bashlog_context_names[index]}" = "${context}" ]; then
      __bashlog_context_index=${index}
      return 0
    fi
  done

  return 1
}

__bashlog_context_resolve_active() {
  if (( $# != 1 )) || ! __bashlog_context_name_valid "$1"; then
    return 64
  fi

  if ! __bashlog_context_find "$1"; then
    return 69
  fi

  if [ "${__bashlog_context_states[__bashlog_context_index]}" != active ]; then
    return 69
  fi

  return 0
}

__bashlog_glob_whole_match() {
  local restore_nocasematch=0
  local status

  if shopt -q nocasematch; then
    restore_nocasematch=1
    shopt -u nocasematch
  fi

  [[ $1 == $2 ]]
  status=$?

  if (( restore_nocasematch )); then
    shopt -s nocasematch
  fi

  return "${status}"
}

__bashlog_ere_match() {
  local restore_nocasematch=0
  local status

  if shopt -q nocasematch; then
    restore_nocasematch=1
    shopt -u nocasematch
  fi

  [[ $1 =~ $2 ]]
  status=$?

  if (( restore_nocasematch )); then
    shopt -s nocasematch
  fi

  return "${status}"
}

__bashlog_fixed_find_next() {
  local input=$1
  local pattern=$2
  local cursor=$3
  local input_length=${#input}
  local pattern_length=${#pattern}
  local start
  local slice

  __bashlog_match_start=-1
  __bashlog_match_length=0

  if (( pattern_length == 0 )); then
    return 2
  fi

  for ((start = cursor; start + pattern_length <= input_length; start++)); do
    slice=${input:start:pattern_length}
    if [ "${slice}" = "${pattern}" ]; then
      __bashlog_match_start=${start}
      __bashlog_match_length=${pattern_length}
      return 0
    fi
  done

  return 1
}

__bashlog_glob_find_next() {
  local input=$1
  local pattern=$2
  local cursor=$3
  local input_length=${#input}
  local start
  local length
  local slice

  __bashlog_match_start=-1
  __bashlog_match_length=0

  for ((start = cursor; start < input_length; start++)); do
    for ((length = input_length - start; length > 0; length--)); do
      slice=${input:start:length}
      if __bashlog_glob_whole_match "${slice}" "${pattern}"; then
        __bashlog_match_start=${start}
        __bashlog_match_length=${length}
        return 0
      fi
    done
  done

  return 1
}

__bashlog_ere_find_next() {
  local input=$1
  local pattern=$2
  local cursor=$3
  local input_length=${#input}
  local start
  local forced_pattern
  local status
  local matched

  __bashlog_match_start=-1
  __bashlog_match_length=0

  for ((start = cursor; start < input_length; start++)); do
    forced_pattern="^.{${start}}(${pattern})"
    __bashlog_ere_match "${input}" "${forced_pattern}"
    status=$?

    if (( status == 2 )); then
      return 2
    fi

    if (( status == 0 )); then
      matched=${BASH_REMATCH[1]-}
      if (( ${#matched} == 0 )); then
        return 2
      fi
      __bashlog_match_start=${start}
      __bashlog_match_length=${#matched}
      return 0
    fi
  done

  return 1
}

__bashlog_rule_matches() {
  local matcher=$1
  local pattern=$2
  local candidate=$3

  case ${matcher} in
    fixed)
      __bashlog_fixed_find_next "${candidate}" "${pattern}" 0
      return $?
      ;;
    glob)
      __bashlog_glob_find_next "${candidate}" "${pattern}" 0
      return $?
      ;;
    ere)
      __bashlog_ere_match "${candidate}" "${pattern}"
      return $?
      ;;
    *)
      return 2
      ;;
  esac
}

__bashlog_glob_has_extglob_operator() {
  local pattern=$1
  local operator

  for operator in '?(' '*(' '+(' '@(' '!('; do
    if __bashlog_fixed_find_next "${pattern}" "${operator}" 0; then
      return 0
    fi
  done

  return 1
}

__bashlog_rule_validate() {
  local matcher=$1
  local pattern=$2
  local replacement=$3
  local status

  if [ -z "${pattern}" ]; then
    return 65
  fi

  case ${matcher} in
    fixed)
      ;;
    glob)
      if __bashlog_glob_has_extglob_operator "${pattern}"; then
        return 65
      fi
      if __bashlog_glob_whole_match '' "${pattern}"; then
        return 65
      fi
      ;;
    ere)
      __bashlog_ere_match '' "${pattern}"
      status=$?
      if (( status == 0 || status == 2 )); then
        return 65
      fi
      ;;
    *)
      return 64
      ;;
  esac

  __bashlog_rule_matches "${matcher}" "${pattern}" "${replacement}"
  status=$?
  if (( status == 0 || status == 2 )); then
    return 65
  fi

  return 0
}

__bashlog_rule_apply() {
  local matcher=$1
  local pattern=$2
  local replacement=$3
  local input=$4
  local input_length=${#input}
  local cursor=0
  local prefix_length
  local status
  local result=

  while (( cursor < input_length )); do
    case ${matcher} in
      fixed) __bashlog_fixed_find_next "${input}" "${pattern}" "${cursor}" ;;
      glob) __bashlog_glob_find_next "${input}" "${pattern}" "${cursor}" ;;
      ere) __bashlog_ere_find_next "${input}" "${pattern}" "${cursor}" ;;
      *) return 70 ;;
    esac
    status=$?

    if (( status == 1 )); then
      break
    fi
    if (( status != 0 || __bashlog_match_length <= 0 )); then
      return 70
    fi

    prefix_length=$((__bashlog_match_start - cursor))
    result="${result}${input:cursor:prefix_length}${replacement}"
    cursor=$((__bashlog_match_start + __bashlog_match_length))
  done

  result="${result}${input:cursor}"
  __bashlog_transform_result=${result}
  return 0
}

__bashlog_context_transform() {
  local context_index=$1
  local candidate=$2
  local index

  for ((index = 0; index < __bashlog_rule_count; index++)); do
    if (( __bashlog_rule_contexts[index] != context_index )); then
      continue
    fi

    if ! __bashlog_rule_apply \
      "${__bashlog_rule_matchers[index]}" \
      "${__bashlog_rule_patterns[index]}" \
      "${__bashlog_rule_replacements[index]}" \
      "${candidate}"; then
      return 70
    fi
    candidate=${__bashlog_transform_result}
  done

  __bashlog_transform_result=${candidate}
  return 0
}

__bashlog_context_verify() {
  local context_index=$1
  local candidate=$2
  local index
  local status

  for ((index = 0; index < __bashlog_rule_count; index++)); do
    if (( __bashlog_rule_contexts[index] != context_index )); then
      continue
    fi

    __bashlog_rule_matches \
      "${__bashlog_rule_matchers[index]}" \
      "${__bashlog_rule_patterns[index]}" \
      "${candidate}"
    status=$?

    if (( status == 0 || status == 2 )); then
      return 70
    fi
  done

  return 0
}

__bashlog_redact_context() {
  local context_index=$1
  local input=$2
  local candidate

  __bashlog_redacted_result=

  if ! __bashlog_context_transform "${context_index}" "${input}"; then
    return 70
  fi
  candidate=${__bashlog_transform_result}

  if ! __bashlog_context_verify "${context_index}" "${candidate}"; then
    return 70
  fi

  __bashlog_redacted_result=${candidate}
  return 0
}

__bashlog_emit_suppression_diagnostic() {
  local context_index=$1
  local diagnostic='bashlog: message suppressed'

  if __bashlog_context_verify "${context_index}" "${diagnostic}"; then
    printf '%s\n' "${diagnostic}" >&2 || :
  fi

  return 0
}

bashlog_redaction_add() {
  local context
  local matcher
  local pattern
  local replacement
  local context_index=-1
  local index
  local validation_status

  if (( $# != 4 )); then
    return 64
  fi

  context=$1
  matcher=$2
  pattern=$3
  replacement=$4

  if ! __bashlog_context_name_valid "${context}"; then
    return 64
  fi

  case ${matcher} in
    fixed | glob | ere) ;;
    *) return 64 ;;
  esac

  if __bashlog_context_find "${context}"; then
    context_index=${__bashlog_context_index}
    if [ "${__bashlog_context_states[context_index]}" != active ]; then
      return 69
    fi
  fi

  if __bashlog_rule_validate "${matcher}" "${pattern}" "${replacement}"; then
    validation_status=0
  else
    validation_status=$?
  fi
  if (( validation_status != 0 )); then
    return "${validation_status}"
  fi

  if (( context_index >= 0 )); then
    for ((index = 0; index < __bashlog_rule_count; index++)); do
      if (( __bashlog_rule_contexts[index] != context_index )); then
        continue
      fi
      if [ "${__bashlog_rule_matchers[index]}" = "${matcher}" ] && \
        [ "${__bashlog_rule_patterns[index]}" = "${pattern}" ]; then
        return 65
      fi
    done
  else
    context_index=${__bashlog_context_count}
    __bashlog_context_names[context_index]=${context}
    __bashlog_context_states[context_index]=active
    __bashlog_context_count=$((__bashlog_context_count + 1))
  fi

  index=${__bashlog_rule_count}
  __bashlog_rule_contexts[index]=${context_index}
  __bashlog_rule_matchers[index]=${matcher}
  __bashlog_rule_patterns[index]=${pattern}
  __bashlog_rule_replacements[index]=${replacement}
  __bashlog_rule_count=$((__bashlog_rule_count + 1))

  return 0
}

bashlog_redaction_context_destroy() {
  local context_index
  local index
  local status

  if (( $# != 1 )); then
    return 64
  fi

  if __bashlog_context_resolve_active "$1"; then
    status=0
  else
    status=$?
  fi
  if (( status != 0 )); then
    return "${status}"
  fi

  context_index=${__bashlog_context_index}
  __bashlog_context_states[context_index]=destroyed

  for ((index = 0; index < __bashlog_rule_count; index++)); do
    if (( __bashlog_rule_contexts[index] != context_index )); then
      continue
    fi

    __bashlog_rule_contexts[index]=-1
    __bashlog_rule_matchers[index]=
    __bashlog_rule_patterns[index]=
    __bashlog_rule_replacements[index]=
  done

  return 0
}

bashlog_redact() {
  local context_index
  local status

  if (( $# != 2 )); then
    return 64
  fi

  if __bashlog_context_resolve_active "$1"; then
    status=0
  else
    status=$?
  fi
  if (( status != 0 )); then
    return "${status}"
  fi
  context_index=${__bashlog_context_index}

  if ! __bashlog_redact_context "${context_index}" "$2"; then
    __bashlog_emit_suppression_diagnostic "${context_index}"
    return 70
  fi

  if ! printf '%s' "${__bashlog_redacted_result}"; then
    return 70
  fi

  return 0
}

declare -g __bashlog_format_mode=auto

declare -g __bashlog_timestamp_mode=off

declare -g __bashlog_color_mode=auto

declare -ga __bashlog_level_style_colors=(red red red red yellow cyan green default)

declare -ga __bashlog_level_style_intensities=(bold bold bold normal normal normal normal dim)

declare -g __bashlog_resolved_format=

declare -g __bashlog_timestamp_value=

declare -g __bashlog_render_result=

declare -g __bashlog_logfmt_quoted_value=

declare -g __bashlog_human_color_code_value=

bashlog_format_get() {
  if (( $# != 0 )); then
    return 64
  fi

  printf '%s\n' "${__bashlog_format_mode}"
}

bashlog_format_set() {
  if (( $# != 1 )); then
    return 64
  fi

  case $1 in
    auto | human | logfmt) __bashlog_format_mode=$1 ;;
    *) return 64 ;;
  esac

  return 0
}

bashlog_timestamp_get() {
  if (( $# != 0 )); then
    return 64
  fi

  printf '%s\n' "${__bashlog_timestamp_mode}"
}

bashlog_timestamp_set() {
  if (( $# != 1 )); then
    return 64
  fi

  case $1 in
    off | utc | local) __bashlog_timestamp_mode=$1 ;;
    *) return 64 ;;
  esac

  return 0
}

bashlog_color_get() {
  if (( $# != 0 )); then
    return 64
  fi

  printf '%s\n' "${__bashlog_color_mode}"
}

bashlog_color_set() {
  if (( $# != 1 )); then
    return 64
  fi

  case $1 in
    never | auto | always) __bashlog_color_mode=$1 ;;
    *) return 64 ;;
  esac

  return 0
}

bashlog_level_style_get() {
  local level_number

  if (( $# != 1 )); then
    return 64
  fi

  __bashlog_level_to_number "$1" || return 64
  level_number=${__bashlog_level_number}
  printf '%s %s\n' \
    "${__bashlog_level_style_colors[level_number]}" \
    "${__bashlog_level_style_intensities[level_number]}"
}

bashlog_level_style_set() {
  local level_number
  local color
  local intensity

  if (( $# != 3 )); then
    return 64
  fi

  __bashlog_level_to_number "$1" || return 64
  level_number=${__bashlog_level_number}
  color=$2
  intensity=$3

  case ${color} in
    default | black | red | green | yellow | blue | magenta | cyan | white) ;;
    *) return 64 ;;
  esac

  case ${intensity} in
    normal | bold | dim) ;;
    *) return 64 ;;
  esac

  __bashlog_level_style_colors[level_number]=${color}
  __bashlog_level_style_intensities[level_number]=${intensity}
  return 0
}

bashlog_level_style_reset() {
  local level_number

  if (( $# > 1 )); then
    return 64
  fi

  if (( $# == 0 )); then
    __bashlog_level_style_colors=(red red red red yellow cyan green default)
    __bashlog_level_style_intensities=(bold bold bold normal normal normal normal dim)
    return 0
  fi

  __bashlog_level_to_number "$1" || return 64
  level_number=${__bashlog_level_number}

  case ${level_number} in
    0 | 1 | 2)
      __bashlog_level_style_colors[level_number]=red
      __bashlog_level_style_intensities[level_number]=bold
      ;;
    3)
      __bashlog_level_style_colors[level_number]=red
      __bashlog_level_style_intensities[level_number]=normal
      ;;
    4)
      __bashlog_level_style_colors[level_number]=yellow
      __bashlog_level_style_intensities[level_number]=normal
      ;;
    5)
      __bashlog_level_style_colors[level_number]=cyan
      __bashlog_level_style_intensities[level_number]=normal
      ;;
    6)
      __bashlog_level_style_colors[level_number]=green
      __bashlog_level_style_intensities[level_number]=normal
      ;;
    7)
      __bashlog_level_style_colors[level_number]=default
      __bashlog_level_style_intensities[level_number]=dim
      ;;
    *) return 64 ;;
  esac

  return 0
}

__bashlog_tag_valid() {
  local LC_ALL=C

  if (( $# != 1 )); then
    return 1
  fi

  [[ $1 =~ ^[A-Za-z0-9_.:-]+$ ]]
}

__bashlog_format_resolve() {
  case ${__bashlog_format_mode} in
    human | logfmt)
      __bashlog_resolved_format=${__bashlog_format_mode}
      ;;
    auto)
      if [[ -t 2 ]]; then
        __bashlog_resolved_format=human
      else
        __bashlog_resolved_format=logfmt
      fi
      ;;
    *)
      __bashlog_resolved_format=
      return 70
      ;;
  esac

  return 0
}

__bashlog_timestamp_utc() {
  local -x TZ=UTC0

  if ! printf -v __bashlog_timestamp_value '%(%Y-%m-%dT%H:%M:%SZ)T'; then
    __bashlog_timestamp_value=
    return 70
  fi

  return 0
}

__bashlog_timestamp_acquire() {
  __bashlog_timestamp_value=

  case ${__bashlog_timestamp_mode} in
    off)
      return 0
      ;;
    utc)
      __bashlog_timestamp_utc
      return $?
      ;;
    local)
      if ! printf -v __bashlog_timestamp_value '%(%Y-%m-%dT%H:%M:%S%z)T'; then
        __bashlog_timestamp_value=
        return 70
      fi
      ;;
    *)
      return 70
      ;;
  esac

  return 0
}

__bashlog_human_color_code() {
  local level_number
  local color
  local intensity
  local color_code=
  local intensity_code=

  if ! __bashlog_level_to_number "$1"; then
    __bashlog_human_color_code_value=
    return 70
  fi
  level_number=${__bashlog_level_number}
  color=${__bashlog_level_style_colors[level_number]}
  intensity=${__bashlog_level_style_intensities[level_number]}

  case ${color} in
    default) color_code= ;;
    black) color_code=30 ;;
    red) color_code=31 ;;
    green) color_code=32 ;;
    yellow) color_code=33 ;;
    blue) color_code=34 ;;
    magenta) color_code=35 ;;
    cyan) color_code=36 ;;
    white) color_code=37 ;;
    *)
      __bashlog_human_color_code_value=
      return 70
      ;;
  esac

  case ${intensity} in
    normal) intensity_code= ;;
    bold) intensity_code=1 ;;
    dim) intensity_code=2 ;;
    *)
      __bashlog_human_color_code_value=
      return 70
      ;;
  esac

  if [[ -n ${intensity_code} && -n ${color_code} ]]; then
    __bashlog_human_color_code_value="${intensity_code};${color_code}"
  else
    __bashlog_human_color_code_value="${intensity_code}${color_code}"
  fi

  return 0
}

__bashlog_human_color_enabled() {
  case ${__bashlog_color_mode} in
    never) return 1 ;;
    always) return 0 ;;
    auto)
      if [[ -t 2 ]]; then
        return 0
      fi
      return 1
      ;;
    *) return 70 ;;
  esac
}

__bashlog_logfmt_quote() {
  local value=${1-}
  local length=${#value}
  local result='"'
  local index
  local character
  local code
  local hex
  local control
  local encoded=0

  for ((index = 0; index < length; index++)); do
    character=${value:index:1}
    case ${character} in
      $'\\') result+="\\\\" ;;
      '"') result+="\\\"" ;;
      $'\t') result+="\\t" ;;
      $'\r') result+="\\r" ;;
      $'\n') result+="\\n" ;;
      *)
        encoded=0
        for ((code = 1; code < 32; code++)); do
          if (( code == 9 || code == 10 || code == 13 )); then
            continue
          fi
          printf -v hex '%02X' "${code}"
          printf -v control '%b' "\\x${hex}"
          if [[ ${character} == "${control}" ]]; then
            result+="\\u00${hex}"
            encoded=1
            break
          fi
        done
        if (( ! encoded )); then
          printf -v control '%b' '\x7F'
          if [[ ${character} == "${control}" ]]; then
            result+="\\u007F"
          else
            result+=${character}
          fi
        fi
        ;;
    esac
  done

  result+='"'
  __bashlog_logfmt_quoted_value=${result}
  return 0
}

__bashlog_render_human() {
  local level=$1
  local timestamp=$2
  local message=$3
  shift 3
  local candidate=
  local level_text=${level}
  local tag
  local color_status

  __bashlog_human_color_enabled
  color_status=$?
  if (( color_status == 70 )); then
    return 70
  fi
  if (( color_status == 0 )); then
    if ! __bashlog_human_color_code "${level}"; then
      return 70
    fi
    if [[ -n ${__bashlog_human_color_code_value} ]]; then
      level_text=$'\033['"${__bashlog_human_color_code_value}"$'m'"${level}"$'\033[0m'
    fi
  fi

  if [[ -n ${timestamp} ]]; then
    candidate="[${timestamp}] "
  fi
  candidate+="${level_text}"

  for tag in "$@"; do
    candidate+=" [${tag}]"
  done

  candidate+=": ${message}"
  __bashlog_render_result=${candidate}
  return 0
}

__bashlog_render_logfmt() {
  local level=$1
  local timestamp=$2
  local message=$3
  shift 3
  local candidate=
  local tag

  if [[ -n ${timestamp} ]]; then
    candidate="ts=${timestamp} "
  fi
  candidate+="level=${level}"

  for tag in "$@"; do
    if __bashlog_tag_valid "${tag}"; then
      candidate+=" tag=${tag}"
    else
      __bashlog_logfmt_quote "${tag}"
      candidate+=" tag=${__bashlog_logfmt_quoted_value}"
    fi
  done

  __bashlog_logfmt_quote "${message}"
  candidate+=" msg=${__bashlog_logfmt_quoted_value}"

  __bashlog_render_result=${candidate}
  return 0
}

__bashlog_render_record() {
  if ! __bashlog_format_resolve; then
    return 70
  fi

  case ${__bashlog_resolved_format} in
    human) __bashlog_render_human "$@" ;;
    logfmt) __bashlog_render_logfmt "$@" ;;
    *) return 70 ;;
  esac
}

bashlog_log() {
  local level
  local level_number
  local context_index=-1
  local context_seen=0
  local format
  local message
  local timestamp
  local candidate
  local status
  local tag
  local index
  local tag_count=0
  local -a tags=()

  if (( $# < 2 )); then
    return 64
  fi

  level=$1
  shift

  case ${level} in
    emergency | alert | critical | error | warning | notice | info | debug) ;;
    *) return 64 ;;
  esac

  if ! __bashlog_level_to_number "${level}"; then
    return 64
  fi
  level_number=${__bashlog_level_number}

  while (( $# > 0 )); do
    case $1 in
      --context)
        if (( context_seen || $# < 2 )); then
          return 64
        fi
        if __bashlog_context_resolve_active "$2"; then
          status=0
        else
          status=$?
        fi
        if (( status != 0 )); then
          return "${status}"
        fi
        context_index=${__bashlog_context_index}
        context_seen=1
        shift 2
        ;;
      --tag)
        if (( $# < 2 )) || ! __bashlog_tag_valid "$2"; then
          return 64
        fi
        tags[tag_count]=$2
        ((tag_count += 1))
        shift 2
        ;;
      --)
        shift
        break
        ;;
      -*)
        return 64
        ;;
      *)
        break
        ;;
    esac
  done

  if (( $# == 0 )); then
    return 64
  fi

  if (( level_number > __bashlog_active_level )); then
    return 0
  fi

  format=$1
  shift

  if printf -v message -- "${format}" "$@" 2>/dev/null; then
    :
  else
    return 64
  fi

  if ! __bashlog_timestamp_acquire; then
    return 70
  fi
  timestamp=${__bashlog_timestamp_value}

  if (( context_seen )); then
    if ! __bashlog_redact_context "${context_index}" "${message}"; then
      __bashlog_emit_suppression_diagnostic "${context_index}"
      return 70
    fi
    message=${__bashlog_redacted_result}

    for ((index = 0; index < tag_count; index++)); do
      tag=${tags[index]}
      if ! __bashlog_redact_context "${context_index}" "${tag}"; then
        __bashlog_emit_suppression_diagnostic "${context_index}"
        return 70
      fi
      tags[index]=${__bashlog_redacted_result}
    done
  fi

  if (( tag_count > 0 )); then
    if ! __bashlog_render_record \
      "${level}" \
      "${timestamp}" \
      "${message}" \
      "${tags[@]}"; then
      if (( context_seen )); then
        __bashlog_emit_suppression_diagnostic "${context_index}"
      fi
      return 70
    fi
  else
    if ! __bashlog_render_record \
      "${level}" \
      "${timestamp}" \
      "${message}"; then
      if (( context_seen )); then
        __bashlog_emit_suppression_diagnostic "${context_index}"
      fi
      return 70
    fi
  fi
  candidate=${__bashlog_render_result}

  if (( context_seen )); then
    if ! __bashlog_context_verify "${context_index}" "${candidate}"; then
      __bashlog_emit_suppression_diagnostic "${context_index}"
      return 70
    fi
  fi

  if ! printf '%s\n' "${candidate}" >&2; then
    return 74
  fi

  return 0
}

bashlog_debug() {
  bashlog_log debug "$@"
}

bashlog_info() {
  bashlog_log info "$@"
}

bashlog_notice() {
  bashlog_log notice "$@"
}

bashlog_warning() {
  bashlog_log warning "$@"
}

bashlog_error() {
  bashlog_log error "$@"
}

bashlog_critical() {
  bashlog_log critical "$@"
}

bashlog_alert() {
  bashlog_log alert "$@"
}

bashlog_emergency() {
  bashlog_log emergency "$@"
}

# shellcheck shell=bash
## @file src/letsencrypt-routeros.bash
## @brief Uploads an existing TLS certificate and private key to RouterOS.
## @details
## Transfers an existing certificate and private key to a MikroTik RouterOS
## device over SSH/SCP, imports both files, and configures supported TLS
## services to use the imported certificate.
##
## Configuration files are trusted executable Bash.  The maintained source may
## be run after `make deps`; generated consumer artifacts embed bashlog and are
## standalone.
## @author Wes Dean
## @see doc/adr/README.md

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  set -euo pipefail
fi

## @var config_file_options
## @brief Default configuration files, in increasing precedence order.
declare -a config_file_options=(".env" "letsencrypt-routeros.settings")

## @var services
## @brief RouterOS services configured to use the imported certificate.
declare -a services=("www-ssl" "api-ssl" "sstp")

## @var ROUTEROS_SSH_OPTIONS
## @brief Additional whitespace-delimited OpenSSH option tokens.
declare ROUTEROS_SSH_OPTIONS="${ROUTEROS_SSH_OPTIONS:-}"

## @var ROUTEROS_USER
## @brief RouterOS administrative username.
declare ROUTEROS_USER="${ROUTEROS_USER:-}"

## @var ROUTEROS_PRIVATE_KEY
## @brief Local SSH private-key path.
declare ROUTEROS_PRIVATE_KEY="${ROUTEROS_PRIVATE_KEY:-}"

## @var ROUTEROS_HOST
## @brief RouterOS hostname or IP address.
declare ROUTEROS_HOST="${ROUTEROS_HOST:-}"

## @var ROUTEROS_SSH_PORT
## @brief RouterOS SSH port.
declare ROUTEROS_SSH_PORT="${ROUTEROS_SSH_PORT:-}"

## @var DOMAIN
## @brief Domain identifier used for certificate paths and RouterOS names.
declare DOMAIN="${DOMAIN:-}"

## @var CERTIFICATE
## @brief Local signed-certificate path.
declare CERTIFICATE="${CERTIFICATE:-}"

## @var KEY
## @brief Local TLS private-key path.
declare KEY="${KEY:-}"

## @var routeros_ssh
## @brief Prepared argv array for SSH calls.
declare -a routeros_ssh=()

## @var routeros_scp
## @brief Prepared argv array for SCP calls.
declare -a routeros_scp=()

# Maintained source loads the prepared dependency.  Built artifacts embed
# bashlog before this source, so this branch is skipped for consumers.
if ! declare -F bashlog_error >/dev/null 2>&1; then
  __routeros_ssl_source_path="${BASH_SOURCE[0]}"
  __routeros_ssl_source_dir="${__routeros_ssl_source_path%/*}"
  if [[ "${__routeros_ssl_source_dir}" == "${__routeros_ssl_source_path}" ]]; then
    __routeros_ssl_source_dir=.
  fi
  __routeros_ssl_source_dir="$(
    cd -- "${__routeros_ssl_source_dir}" && pwd
  )"
  __routeros_ssl_bashlog="${__routeros_ssl_source_dir}/../vendor/bashlog.bash"

  if [[ ! -r "${__routeros_ssl_bashlog}" ]]; then
    printf '%s\n' \
      'Missing vendor/bashlog.bash; run make deps or use a built artifact.' \
      >&2
    if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
      exit 1
    fi
    return 1
  fi

  # shellcheck disable=SC1090
  source "${__routeros_ssl_bashlog}"
  unset __routeros_ssl_source_path __routeros_ssl_source_dir
  unset __routeros_ssl_bashlog
fi

## @fn usage_help()
## @brief Writes command usage and configuration-file names.
## @details
## Describes positional arguments, supported short options, and default
## configuration-file discovery.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Usage text is written to STDOUT.
## @par STDERR
## Nothing is intentionally written to STDERR.
##
## @returns Human-readable usage text.
## @retval 0 Usage text was written.
usage_help() {
  printf '%s\n' \
    "$0 [RouterOS User] [RouterOS Host] [SSH Port] [SSH Private Key] [Domain]" \
    "" \
    "or" \
    "" \
    "$0" \
    "  -C [Certificate]" \
    "  -d [Domain]" \
    "  -h" \
    "  -H [RouterOS Host]" \
    "  -K [Certificate Private Key]" \
    "  -k [SSH Private Key]" \
    "  -o [RouterOS SSH Options]" \
    "  -p [RouterOS SSH Port]" \
    "  -u [RouterOS User]" \
    "" \
    "or use configuration files:"

  local config_file
  for config_file in "${config_file_options[@]}"; do
    printf '* %s\n' "${config_file}"
  done
}

## @fn load_configuration()
## @brief Loads explicit or discovered trusted Bash configuration.
## @details
## If CONFIG_FILE is non-empty, only that file is sourced.  Otherwise existing
## default files are sourced in array order, so later files have higher
## precedence.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## Configuration errors are logged to STDERR.
##
## @returns Nothing is written to STDOUT.
## @retval 0 Configuration loading succeeded or no default files existed.
## @retval 1 An explicit configuration file could not be loaded.
load_configuration() {
  local explicit_config="${CONFIG_FILE:-}"
  local config_file

  if [[ -n "${explicit_config}" ]]; then
    if [[ ! -f "${explicit_config}" ]]; then
      bashlog_error 'Could not load CONFIG_FILE %s' "${explicit_config}"
      return 1
    fi
    # shellcheck disable=SC1090
    source "${explicit_config}"
    return 0
  fi

  for config_file in "${config_file_options[@]}"; do
    if [[ -f "${config_file}" ]]; then
      # shellcheck disable=SC1090
      source "${config_file}"
    fi
  done
}

## @fn resolve_configuration()
## @brief Resolves option/configuration values and positional fallbacks.
## @details
## Values already set by the environment, configuration files, or command-line
## options win.  Remaining positional values fill user, host, port, SSH key,
## and domain in that order.  The user defaults to admin only after positional
## resolution.  Certificate paths are derived only after DOMAIN is known.
##
## @param arguments[] Remaining positional command-line arguments.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## Missing required values are logged to STDERR.
##
## @returns Nothing is written to STDOUT.
## @retval 0 Required configuration was resolved.
## @retval 1 A required value is missing or extra positionals were supplied.
resolve_configuration() {
  if (( $# > 5 )); then
    bashlog_error 'Too many positional arguments'
    return 1
  fi

  ROUTEROS_USER="${ROUTEROS_USER:-${1:-admin}}"
  ROUTEROS_HOST="${ROUTEROS_HOST:-${2:-}}"
  ROUTEROS_SSH_PORT="${ROUTEROS_SSH_PORT:-${3:-}}"
  ROUTEROS_PRIVATE_KEY="${ROUTEROS_PRIVATE_KEY:-${4:-}}"
  DOMAIN="${DOMAIN:-${5:-}}"

  if [[ -z "${ROUTEROS_HOST}" ]]; then
    bashlog_error 'No RouterOS hostname was provided'
    return 1
  fi
  if [[ -z "${ROUTEROS_SSH_PORT}" ]]; then
    bashlog_error 'No RouterOS SSH port was provided'
    return 1
  fi
  if [[ -z "${ROUTEROS_PRIVATE_KEY}" ]]; then
    bashlog_error 'No SSH private key was provided'
    return 1
  fi
  if [[ -z "${DOMAIN}" ]]; then
    bashlog_error 'No certificate domain was provided'
    return 1
  fi

  CERTIFICATE="${CERTIFICATE:-/etc/letsencrypt/live/${DOMAIN}/cert.pem}"
  KEY="${KEY:-/etc/letsencrypt/live/${DOMAIN}/privkey.pem}"
}

## @fn validate_routeros_name()
## @brief Validates a value before RouterOS command interpolation.
## @details
## Accepts only ASCII letters, digits, underscore, dot, and hyphen.  The first
## character must be alphanumeric or underscore.  This intentionally rejects
## RouterOS syntax metacharacters instead of attempting command-language
## escaping.
##
## @param value Candidate RouterOS-safe value.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## Nothing is written to STDERR.
##
## @returns Nothing is written to STDOUT.
## @retval 0 The value is safe for the supported interpolation sites.
## @retval 1 The value is empty or contains a disallowed character.
validate_routeros_name() {
  local value="${1:-}"
  [[ "${value}" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]*$ ]]
}

## @fn validate_configuration()
## @brief Validates configuration used at local and RouterOS command boundaries.
## @details
## Validates the username, host, numeric SSH port, and domain before remote
## commands are constructed.  Domain-derived remote filenames and certificate
## names inherit the validated domain grammar.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## Validation failures are logged to STDERR.
##
## @returns Nothing is written to STDOUT.
## @retval 0 Configuration is valid.
## @retval 1 Configuration is invalid.
validate_configuration() {
  if [[ ! "${ROUTEROS_USER}" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]*$ ]]; then
    bashlog_error 'Unsafe RouterOS username: %s' "${ROUTEROS_USER}"
    return 1
  fi

  if [[ ! "${ROUTEROS_HOST}" =~ ^[A-Za-z0-9_.:%\[\]-]+$ ]]; then
    bashlog_error 'Unsafe RouterOS host: %s' "${ROUTEROS_HOST}"
    return 1
  fi

  if [[ ! "${ROUTEROS_SSH_PORT}" =~ ^[0-9]+$ ]] ||
    (( ROUTEROS_SSH_PORT < 1 || ROUTEROS_SSH_PORT > 65535 )); then
    bashlog_error 'Invalid RouterOS SSH port: %s' "${ROUTEROS_SSH_PORT}"
    return 1
  fi

  if ! validate_routeros_name "${DOMAIN}"; then
    bashlog_error 'Unsafe certificate domain identifier: %s' "${DOMAIN}"
    return 1
  fi
}

## @fn build_transport_commands()
## @brief Builds argv-safe SSH and SCP command arrays.
## @details
## Tokenizes ROUTEROS_SSH_OPTIONS on shell whitespace without eval and appends
## the resulting tokens to both OpenSSH command arrays.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## Nothing is written to STDERR.
##
## @returns Nothing is written to STDOUT.
## @retval 0 Transport command arrays were constructed.
build_transport_commands() {
  local -a extra_options=()

  if [[ -n "${ROUTEROS_SSH_OPTIONS}" ]]; then
    read -r -a extra_options <<<"${ROUTEROS_SSH_OPTIONS}"
  fi

  routeros_ssh=(
    ssh
    -i "${ROUTEROS_PRIVATE_KEY}"
    -p "${ROUTEROS_SSH_PORT}"
    "${extra_options[@]}"
    "${ROUTEROS_USER}@${ROUTEROS_HOST}"
  )

  routeros_scp=(
    scp
    -q
    -P "${ROUTEROS_SSH_PORT}"
    -i "${ROUTEROS_PRIVATE_KEY}"
    "${extra_options[@]}"
  )
}

## @fn verify_connection()
## @brief Verifies the configured RouterOS SSH connection.
## @details
## Executes a non-mutating RouterOS resource command through the prepared SSH
## argv array.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Connection progress and remote output are written to STDOUT.
## @par STDERR
## Connection failures are logged to STDERR.
##
## @returns Human-readable connection progress.
## @retval 0 The RouterOS command completed successfully.
## @retval 1 The RouterOS command failed.
verify_connection() {
  printf '%s\n' 'Checking connection to RouterOS'
  if "${routeros_ssh[@]}" "/system resource print"; then
    printf '%s\n' '  Connected.'
    return 0
  fi

  bashlog_error \
    'Could not connect to RouterOS host=%s port=%s' \
    "${ROUTEROS_HOST}" "${ROUTEROS_SSH_PORT}"
  return 1
}

## @fn verify_requirements()
## @brief Verifies that local certificate material is accessible.
## @details
## Checks existence and readability for the certificate and TLS private key.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Requirement-check progress is written to STDOUT.
## @par STDERR
## Requirement failures are logged to STDERR.
##
## @returns Human-readable requirement-check progress.
## @retval 0 Both files exist and are readable.
## @retval 1 The certificate does not exist.
## @retval 2 The certificate is not readable.
## @retval 3 The private key does not exist.
## @retval 4 The private key is not readable.
verify_requirements() {
  printf "Looking for '%s'\n" "${CERTIFICATE}"
  if [[ ! -f "${CERTIFICATE}" ]]; then
    bashlog_error "CERTIFICATE '%s' NOT FOUND" "${CERTIFICATE}"
    return 1
  fi
  if [[ ! -r "${CERTIFICATE}" ]]; then
    bashlog_error "CERTIFICATE '%s' NOT READABLE" "${CERTIFICATE}"
    return 2
  fi
  printf '%s\n' 'Found' 'Readable'

  printf "Looking for key '%s'\n" "${KEY}"
  if [[ ! -f "${KEY}" ]]; then
    bashlog_error "KEY '%s' NOT FOUND" "${KEY}"
    return 3
  fi
  if [[ ! -r "${KEY}" ]]; then
    bashlog_error "KEY '%s' NOT READABLE" "${KEY}"
    return 4
  fi
  printf '%s\n' 'Found' 'Readable'
}

## @fn upload_certificate()
## @brief Uploads and imports the configured certificate.
## @details
## Applies certificate-specific defaults and delegates to upload_file().
##
## @param local_file Local certificate path; defaults to CERTIFICATE.
## @param remote_file RouterOS upload filename; defaults to DOMAIN.pem.
## @param cert_name RouterOS certificate name; defaults to DOMAIN.pem_0.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Processing progress is written to STDOUT.
## @par STDERR
## upload_file() diagnostics may be written to STDERR.
##
## @returns Human-readable processing progress.
## @retval 0 The certificate was processed successfully.
## @note Non-zero statuses from upload_file() are propagated unchanged.
upload_certificate() {
  local local_file="${1:-${CERTIFICATE}}"
  local remote_file="${2:-${DOMAIN}.pem}"
  local cert_name="${3:-${DOMAIN}.pem_0}"

  printf '%s\n' 'Processing certificate'
  upload_file "${local_file}" "${remote_file}" "${cert_name}" || return $?
  printf '%s\n' 'Finished processing certificate'
}

## @fn upload_key()
## @brief Uploads and imports the configured TLS private key.
## @details
## Applies key-specific defaults and preserves upload_file() failure status.
##
## @param local_file Local private-key path; defaults to KEY.
## @param remote_file RouterOS upload filename; defaults to DOMAIN.key.
## @param cert_name RouterOS key name; defaults to DOMAIN.key_0.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Processing progress is written to STDOUT.
## @par STDERR
## upload_file() diagnostics may be written to STDERR.
##
## @returns Human-readable processing progress.
## @retval 0 The private key was processed successfully.
## @note Non-zero statuses from upload_file() are propagated unchanged.
upload_key() {
  local local_file="${1:-${KEY}}"
  local remote_file="${2:-${DOMAIN}.key}"
  local cert_name="${3:-${DOMAIN}.key_0}"

  printf '%s\n' 'Processing key'
  upload_file "${local_file}" "${remote_file}" "${cert_name}" || return $?
  printf '%s\n' 'Finished processing key'
}

## @fn upload_file()
## @brief Uploads one local file and imports it into RouterOS.
## @details
## Best-effort removal of an existing certificate-store entry precedes SCP.
## SCP completion is synchronous, so no fixed sleep is required before import.
##
## @param local_file Local certificate or private-key path.
## @param remote_file RouterOS upload filename.
## @param cert_name Existing RouterOS certificate-store name to replace.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Upload and import progress is written to STDOUT.
## @par STDERR
## Removal warnings and transfer/import errors are logged to STDERR.
##
## @returns Human-readable upload and import progress.
## @retval 0 The file was uploaded and imported successfully.
## @retval 1 SCP failed.
## @retval 2 RouterOS import failed.
## @retval 64 A RouterOS-interpolated name is unsafe.
upload_file() {
  local local_file="${1?Error: no local file provided}"
  local remote_file="${2?Error: no remote file provided}"
  local cert_name="${3?Error: no cert_name provided}"

  if ! validate_routeros_name "${remote_file}" ||
    ! validate_routeros_name "${cert_name}"; then
    bashlog_error 'Unsafe RouterOS filename or certificate name'
    return 64
  fi

  printf 'Processing %s => %s [%s]\n' \
    "${local_file}" "${remote_file}" "${cert_name}"

  printf 'Remove previous cert (%s)\n' "${cert_name}"
  if "${routeros_ssh[@]}" \
    "/certificate remove [find name=\"${cert_name}\"]"; then
    printf '%s\n' '  Previous cert removed.'
  else
    bashlog_warning 'Could not remove previous certificate %s' "${cert_name}"
  fi

  printf '%s\n' 'Upload file to RouterOS'
  if "${routeros_scp[@]}" \
    "${local_file}" \
    "${ROUTEROS_USER}@${ROUTEROS_HOST}:${remote_file}"; then
    printf '%s\n' '  New file uploaded.'
  else
    bashlog_error 'Could not upload new file %s' "${remote_file}"
    return 1
  fi

  printf 'Import %s to %s\n' "${remote_file}" "${cert_name}"
  if "${routeros_ssh[@]}" \
    "/certificate import file-name=\"${remote_file}\" passphrase=\"\""; then
    printf '%s\n' '  File imported.'
  else
    bashlog_error 'Could not import uploaded file %s' "${remote_file}"
    return 2
  fi

  printf 'Done processing %s\n' "${local_file}"
}

## @fn delete_file()
## @brief Removes an uploaded file from the RouterOS filesystem.
## @details
## Uses a name lookup so an absent file is a no-op while transport/RouterOS
## failures remain observable.
##
## @param filename RouterOS filename to remove.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Deletion progress is written to STDOUT.
## @par STDERR
## Deletion failures are logged to STDERR.
##
## @returns Human-readable deletion progress.
## @retval 0 The deletion command completed successfully.
## @retval 1 The deletion command failed.
## @retval 64 The filename is unsafe.
delete_file() {
  local filename="${1?Error: no filename specified}"

  if ! validate_routeros_name "${filename}"; then
    bashlog_error 'Unsafe RouterOS filename: %s' "${filename}"
    return 64
  fi

  printf "Delete file '%s'\n" "${filename}"
  if "${routeros_ssh[@]}" "/file remove [find name=\"${filename}\"]"; then
    printf '%s\n' '  File deleted.'
    return 0
  fi

  bashlog_error 'Could not delete RouterOS file %s' "${filename}"
  return 1
}

## @fn configure_services()
## @brief Configures supported RouterOS services to use a certificate.
## @details
## Updates www-ssl, api-ssl, and SSTP using the supplied safe certificate name.
##
## @param cert_name RouterOS certificate name; defaults to DOMAIN.pem_0.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Service progress is written to STDOUT.
## @par STDERR
## Service failures are logged to STDERR.
##
## @returns Human-readable service-configuration progress.
## @retval 0 All configured services were updated.
## @retval 1 www-ssl configuration failed.
## @retval 2 api-ssl configuration failed.
## @retval 3 SSTP configuration failed.
## @retval 64 A service or certificate name is unsupported.
configure_services() {
  local cert_name="${1:-${DOMAIN}.pem_0}"
  local service
  local service_number=0

  if ! validate_routeros_name "${cert_name}"; then
    bashlog_error 'Unsafe RouterOS certificate name: %s' "${cert_name}"
    return 64
  fi

  printf '%s\n' 'Configuring services'
  for service in "${services[@]}"; do
    printf 'Configuring %s to use %s\n' "${service}" "${cert_name}"

    case "${service}" in
      www-ssl | api-ssl)
        if ! "${routeros_ssh[@]}" \
          "/ip service set ${service} certificate=\"${cert_name}\""; then
          bashlog_error 'Could not configure service %s' "${service}"
          return $((service_number + 1))
        fi
        printf '%s\n' '  Service configuration complete.'
        ;;
      sstp)
        if ! "${routeros_ssh[@]}" \
          "/interface sstp-server server set certificate=\"${cert_name}\""; then
          bashlog_error 'Could not configure SSTP'
          return $((service_number + 1))
        fi
        printf '%s\n' '  SSTP configuration complete.'
        ;;
      *)
        bashlog_error 'Unknown service %s' "${service}"
        return 64
        ;;
    esac

    ((service_number += 1))
  done
}

## @fn remove_remote_files()
## @brief Attempts both remote-file deletions and preserves failure status.
## @details
## Each deletion is attempted even when the other fails so cleanup is
## best-effort but observable.
##
## @param certificate_file RouterOS certificate upload filename.
## @param key_file RouterOS private-key upload filename.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## delete_file() progress is written to STDOUT.
## @par STDERR
## delete_file() diagnostics are written to STDERR.
##
## @returns Human-readable deletion progress.
## @retval 0 Both deletion commands completed successfully.
## @retval 1 One or both deletion commands failed.
remove_remote_files() {
  local certificate_file="${1:-${DOMAIN}.pem}"
  local key_file="${2:-${DOMAIN}.key}"
  local status=0

  delete_file "${certificate_file}" || status=1
  delete_file "${key_file}" || status=1
  return "${status}"
}

## @fn setup()
## @brief Removes stale uploaded certificate and key files.
## @details
## Delegates to remove_remote_files() before a new upload begins.
##
## @param certificate_file RouterOS certificate upload filename.
## @param key_file RouterOS private-key upload filename.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Cleanup progress is written to STDOUT.
## @par STDERR
## Cleanup failures are logged to STDERR.
##
## @returns Human-readable cleanup progress.
## @retval 0 Both stale-file deletion commands completed.
## @retval 1 One or both deletion commands failed.
setup() {
  remove_remote_files "${1:-${DOMAIN}.pem}" "${2:-${DOMAIN}.key}"
}

## @fn cleanup()
## @brief Removes uploaded certificate and key files after processing.
## @details
## Delegates to remove_remote_files() after success or a partial failure.
##
## @param certificate_file RouterOS certificate upload filename.
## @param key_file RouterOS private-key upload filename.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Cleanup progress is written to STDOUT.
## @par STDERR
## Cleanup failures are logged to STDERR.
##
## @returns Human-readable cleanup progress.
## @retval 0 Both uploaded-file deletion commands completed.
## @retval 1 One or both deletion commands failed.
cleanup() {
  remove_remote_files "${1:-${DOMAIN}.pem}" "${2:-${DOMAIN}.key}"
}

## @fn main()
## @brief Orchestrates configuration, transfer, import, service update, cleanup.
## @details
## Loads trusted configuration, applies CLI and positional precedence, validates
## the command boundary, checks local requirements/connectivity, performs the
## update, and always attempts final cleanup after upload processing begins.
##
## @param arguments[] Command-line options and positional configuration values.
##
## @par STDIN
## Nothing is intentionally read from STDIN.
## @par STDOUT
## Progress and remote output may be written to STDOUT.
## @par STDERR
## Errors and warnings are emitted through bashlog.
##
## @returns Human-readable orchestration progress.
## @retval 0 The complete workflow succeeded.
## @retval 1 Configuration or local requirements failed.
## @retval 2 RouterOS connectivity verification failed.
## @retval 3 Initial remote-file cleanup failed.
## @retval 4 Certificate upload/import failed.
## @retval 5 Private-key upload/import failed.
## @retval 6 RouterOS service configuration failed.
## @retval 7 Final remote-file cleanup failed.
main() {
  local arg
  local opt
  local primary_status=0
  local cleanup_status=0
  local certificate_remote
  local key_remote

  for arg in "$@"; do
    if [[ "${arg}" == "-h" ]]; then
      usage_help
      return 0
    fi
  done

  load_configuration || return 1

  OPTIND=1
  while getopts ":C:d:H:hK:k:o:p:u:" opt; do
    case "${opt}" in
      C) CERTIFICATE="${OPTARG}" ;;
      d) DOMAIN="${OPTARG}" ;;
      H) ROUTEROS_HOST="${OPTARG}" ;;
      h)
        usage_help
        return 0
        ;;
      K) KEY="${OPTARG}" ;;
      k) ROUTEROS_PRIVATE_KEY="${OPTARG}" ;;
      o) ROUTEROS_SSH_OPTIONS="${OPTARG}" ;;
      p) ROUTEROS_SSH_PORT="${OPTARG}" ;;
      u) ROUTEROS_USER="${OPTARG}" ;;
      :)
        bashlog_error 'Option -%s requires an argument' "${OPTARG}"
        return 1
        ;;
      \?)
        bashlog_error 'Unknown option -%s' "${OPTARG}"
        usage_help >&2
        return 1
        ;;
    esac
  done
  shift "$((OPTIND - 1))"

  resolve_configuration "$@" || return 1
  validate_configuration || return 1
  build_transport_commands

  verify_requirements || return 1
  verify_connection || return 2

  certificate_remote="${DOMAIN}.pem"
  key_remote="${DOMAIN}.key"

  setup "${certificate_remote}" "${key_remote}" || return 3

  if ! upload_certificate \
    "${CERTIFICATE}" "${certificate_remote}" "${DOMAIN}.pem_0"; then
    primary_status=4
  elif ! upload_key "${KEY}" "${key_remote}" "${DOMAIN}.key_0"; then
    primary_status=5
  elif ! configure_services "${DOMAIN}.pem_0"; then
    primary_status=6
  fi

  if ! cleanup "${certificate_remote}" "${key_remote}"; then
    cleanup_status=7
  fi

  if (( primary_status != 0 )); then
    if (( cleanup_status != 0 )); then
      bashlog_error \
        'Cleanup also failed after primary workflow status %s' \
        "${primary_status}"
    fi
    return "${primary_status}"
  fi

  return "${cleanup_status}"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  main "$@"
else
  return 0
fi
